version: "3.9"

networks:
  demo-server:
    driver: bridge

services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - demo-server
    ports:
      - 3000:3000
