version: "3.9"

networks:
  demo-server:
    driver: bridge

services:
  app_1:
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev
    # env_file: ../file_upload/app/.env
    networks:
      - demo-server
    ports:
      - 3000:3000

#   visualization_api:
#     build:
#       context: ../visualization
#       dockerfile: Dockerfile
#       # target: dev
#     env_file: ../visualization/deploy.env
#     networks:
#       - solver
#     ports:
#       - 9505:9505

#   idh_api:
#     build:
#       context: ../solver_mathstep
#       dockerfile: Dockerfile
#     networks:
#       - solver
#     ports:
#       - 3001:3001

#   node-api:
#     build:
#       context: ../bytelearn-mathsteps
#       dockerfile: ./bin/Dockerfile.deployment
#     command: bash -c "bin/start.sh" # target: dev
#     networks:
#       - solver
#     ports:
#       - 3401:3400

#   solver:
#     build:
#       context: .
#       dockerfile: ./bin/Dockerfile.deployment
#       # target: dev
#     env_file: ./bin/${APP_ENV}.env
#     environment:
#       - ENV=dev
#     command: bash -c "bin/start.sh"
#     volumes:
#       - ~/logs/bytelearn-mpu-solver-expts:/app/logs
#     networks:
#       - solver
#     ports:
#       - 9500:9500
#     depends_on:
#       - visualization_api
#       - idh_api
#       - node-api
#       - file_uploader
# version: "3.9"

# networks:
#   solver:
#     driver: bridge



# services:
#   file_uploader:
#     build:
#       context: ../file_upload
#       dockerfile: Dockerfile
#       # target: dev
#     # env_file: ../file_upload/app/.env
#     networks:
#       - solver
#     ports:
#       - 5000:5000

#   visualization_api:
#     build:
#       context: ../visualization
#       dockerfile: Dockerfile
#       # target: dev
#     env_file: ../visualization/deploy.env
#     networks:
#       - solver
#     ports:
#       - 9505:9505

#   idh_api:
#     build:
#       context: ../solver_mathstep
#       dockerfile: Dockerfile
#     networks:
#       - solver
#     ports:
#       - 3001:3001

#   node-api:
#     build:
#       context: ../bytelearn-mathsteps
#       dockerfile: ./bin/Dockerfile.deployment
#     command: bash -c "bin/start.sh" # target: dev
#     networks:
#       - solver
#     ports:
#       - 3401:3400

#   solver:
#     build:
#       context: .
#       dockerfile: ./bin/Dockerfile.deployment
#       # target: dev
#     env_file: ./bin/${APP_ENV}.env
#     environment:
#       - ENV=dev
#     command: bash -c "bin/start.sh"
#     volumes:
#       - ~/logs/bytelearn-mpu-solver-expts:/app/logs
#     networks:
#       - solver
#     ports:
#       - 9500:9500
#     depends_on:
#       - visualization_api
#       - idh_api
#       - node-api
#       - file_uploader
